import Foundation

/// Minimal localization wrapper for RenJistrolyUI.
/// Currently defaults to Chinese (the original UI language of this module).
/// EN translations are provided for future bilingual support.
public enum RenJistrolyStrings {
    private static var preferredLanguage: String {
        UserDefaults.standard.string(forKey: "renjistroly.language") ?? "zh"
    }

    public static func text(_ key: String) -> String {
        if preferredLanguage == "en", let value = en[key] {
            return value
        }
        return zh[key] ?? key
    }

    private static let en: [String: String] = [
        "auditViewTitle": "Action Audit",
        "auditViewSubtitle": "All actions triggered in safe mode",
        "auditExport": "Export",
        "auditSearchPlaceholder": "Search action records…",
        "auditTotal": "Total",
        "auditDenied": "Blocked",
        "auditPending": "Pending Review",
        "auditHeader": "Time\tAction\tCategory\tRisk\tStatus\tDetail",
        "auditStatusApproved": "Approved",
        "auditStatusDenied": "Blocked",
        "auditStatusPending": "Pending",
        "auditStatusFailed": "Failed",

        "dashboardTitle": "Context Dashboard",
        "dashboardSubtitle": "Current environment information and risk overview",
        "dashboardRefreshed": "Context refreshed",
        "dashboardScreenWindow": "Screen & Window",
        "dashboardClipboardRisk": "Clipboard Risk",
        "dashboardClipboardSafe": "Current clipboard content is safe",
        "dashboardPermissions": "Permission Status",
        "dashboardLastCheck": "Last check: ",
        "dashboardDevContext": "Development Context",
        "dashboardUncommitted": " uncommitted",
        "dashboardWorkspaceClean": "Workspace clean",
        "dashboardRefreshContext": "Refresh Context",
        "dashboardCheckPassed": "All passed",
        "dashboardCheckRunning": "Running…",
        "dashboardCheckFailed": "%d failed",

        "assistantConfirmAction": "Confirm Action",
        "assistantExecute": "Execute",
        "assistantCancel": "Cancel",
        "assistantQuitTitle": "Quit RenJistroly",
        "assistantQuitMessage": "Are you sure you want to quit RenJistroly?",
        "assistantQuit": "Quit",
        "assistantSidebar": "Sidebar",
        "assistantListening": "Listening",
        "assistantTranscribing": "Transcribing",
        "assistantNewConversation": "New Conversation",
        "assistantRefreshContext": "Refresh Context",
        "assistantReadScreen": "Read Screen",
        "assistantPermissions": "Permissions",
        "assistantBaseCenter": "Base Center",
        "assistantSettings": "Settings",
        "assistantContextPanel": "Context Panel",
        "assistantExit": "Exit",
        "assistantInputPlaceholder": "Type a message or use the microphone",
        "assistantContextSection": "Context",
        "assistantCurrentApp": "Current App",
        "assistantUnknown": "Unknown",
        "assistantNoWindowTitle": "No window title",
        "assistantListeningStatus": "Listening...",
        "assistantLockedListening": "Continuous listening...",
        "assistantSpeaking": "Speaking...",
        "assistantProcessing": "Processing...",
        "assistantExecutingPlan": "Executing plan...",
        "assistantAwaitingApproval": "Awaiting approval",
        "assistantPlanCompleted": "Plan completed",
        "assistantPlanFailed": "Plan failed",
        "assistantReady": "Ready",
        "assistantLoading": "Loading...",
        "assistantContextRunningApps": "Running",
        "assistantContextFocusedElement": "Focused Element",
        "assistantPermissionAccessibility": "Accessibility",
        "assistantPermissionMicrophone": "Microphone",
        "assistantPermissionScreenRecording": "Screen Recording",
        "assistantContextRole": "Role",
        "assistantContextTitle": "Title",
        "assistantContextSelected": "Selected",
        "mainTabControlPanel": "Control Panel",
        "mainTabAuditLog": "Audit Log",
        "mainTabDashboard": "Context",
        "mainTabModeCountFormat": "%d/%d security modes enabled",
        "appDelegateAlreadyRunningTitle": "RenJistroly is already running",
        "appDelegateDuplicateInstanceBody": "Another RenJistroly instance is already running. Multiple instances can cause Gate file conflicts. Quit this instance?",
        "appDelegateContinueRunning": "Continue Running",
        "appDelegateSafeModeTitle": "RenJistroly entered safe mode",
        "appDelegateSafeModeBody": "The app has crashed multiple times. Some automatic features (e.g. MCP auto-start) have been disabled.\n\nTo reset crash history, delete ~/Library/Logs/RenJistroly/crash_history.json",
        "appDelegateAcknowledge": "Acknowledge",
        "appDelegateSettingsWindowTitle": "RenJistroly Settings",
        "appDelegateAppNapReason": "RenJistroly needs background activity to maintain voice and screen monitoring",
        "appDelegatePermissionTitle": "Accessibility Permission Required",
        "appDelegatePermissionBody": "RenJistroly needs Accessibility permission to control your Mac.\n\nPlease go to System Settings > Privacy & Security > Accessibility, add and enable RenJistroly.",
        "appDelegateOpenSystemSettings": "Open System Settings",
        "appDelegateLater": "Later",

        "settingsTabGeneral": "General",
        "settingsTabAIModel": "AI Model",
        "settingsTabSecurity": "Security",
        "settingsTabDeveloper": "Developer",
        "settingsTabPermissions": "Permissions",
        "settingsTabAbout": "About",
        "settingsGeneralStartupAppearance": "Startup & Appearance",
        "settingsLaunchAtLogin": "Launch at login",
        "settingsShowMenuBarIcon": "Show menu bar icon",
        "settingsEnableFloatingPanel": "Enable floating panel",
        "settingsDefaultAIProvider": "Default AI Provider",
        "settingsDefaultModel": "Default Model",
        "settingsInteraction": "Interaction",
        "settingsVoiceReply": "Enable voice reply",
        "settingsContinuousVoice": "Continuous voice mode",
        "settingsGlobalHotkey": "Global Hotkey",
        "settingsHotkeyValue": "Hold ⌥ Space",
        "settingsVoiceLanguage": "Voice Language",
        "settingsChinese": "中文",
        "settingsJapanese": "日本語",
        "settingsToolAutoExecutePolicy": "Tool Auto-Execute Policy",
        "settingsToolPolicyDescription": "Controls whether the AI assistant needs confirmation for system operations.",
        "settingsLowRiskAuto": "Low Risk \u{00B7} Auto Execute",
        "settingsLowRiskDesc": "Read-only: read files, list directories, system info, Git status, etc.",
        "settingsMediumRiskAuto": "Medium Risk \u{00B7} Auto Execute",
        "settingsMediumRiskDesc": "UI interaction: open apps, click elements, key presses, menu navigation, etc.",
        "settingsHighRiskAuto": "High Risk \u{00B7} Auto Execute",
        "settingsHighRiskDesc": "System modification: write files, Shell commands, text input, drag and drop, etc.",
        "settingsPresets": "Presets",
        "settingsPresetDefault": "Default",
        "settingsPresetDefaultDesc": "Low risk auto, medium/high risk confirm",
        "settingsPresetPermissive": "Permissive",
        "settingsPresetPermissiveDesc": "Low/medium risk auto, high risk confirm only",
        "settingsPresetStrict": "Strict",
        "settingsPresetStrictDesc": "All require confirmation",
        "settingsAnthropic": "Anthropic (Claude)",
        "settingsApiKeyPlaceholder": "API Key",
        "settingsGetApiKeyPrefix": "Get API Key:",
        "settingsLocalMLX": "Local Model (MLX)",
        "settingsMLXStatus": "Status",
        "settingsMLXAvailable": "Apple Silicon \u{00B7} Available",
        "settingsMLXDescription": "Local models run on Apple Silicon, no network required, data stays on device.",
        "settingsDevMode": "Developer Mode",
        "settingsEnableDevMode": "Enable Developer Mode",
        "settingsProjectPath": "Project Path",
        "settingsDetect": "Detect",
        "settingsOCREngine": "OCR Engine",
        "settingsOCREnginePicker": "Text Recognition Engine",
        "settingsClaudeCodeReady": "Claude Code ready",
        "settingsClaudeCodeNotDetected": "Claude Code not detected",
        "settingsClaudeCodeRefresh": "Refresh",
        "settingsCurrentProject": "Current Project",
        "settingsClaudeCodePromptPlaceholder": "Task for Claude Code, e.g.: Read the current Swift Package and summarize unfinished capabilities",
        "settingsSavePath": "Save Path",
        "settingsLaunchClaudeTask": "Launch Claude Task",
        "settingsClaudeCodeHelp": "Claude Code will execute the development task in the current project directory and stream output back to the conversation.",
        "settingsClaudeCodeNotInstalledHelp": "Please ensure Claude Code CLI is installed and fill in the executable path above.",
        "settingsQuickActions": "Quick Actions",
        "settingsBuildResult": "Build complete: %@",
        "settingsBuild": "Build",
        "settingsTestResult": "Test complete: %@",
        "settingsTest": "Test",
        "settingsRecentBuild": "Recent build: %@",
        "settingsRecentTest": "Recent test: %@",
        "settingsSelfUpdate": "Self-Update",
        "settingsHelperLabel": "Helper: %@",
        "settingsCheck": "Check",
        "settingsCurrentVersion": "Current Version",
        "settingsInstallHelper": "Install Helper",
        "settingsNoResponse": "No response",
        "settingsVerifySignature": "Verify Signature",
        "settingsPermissionStatus": "Permission Status",
        "settingsRefresh": "Refresh",
        "settingsSystemPermissions": "System Permissions",
        "settingsNotRefreshed": "Not refreshed yet.",
        "settingsPrivacy": "Privacy",
        "settingsPrivacyText": "All voice processing is done locally. Sensitive conversation data never leaves the device. Cloud API calls only send necessary conversation content, secured by your own API Key.",
        "settingsVersion": "Version",
        "settingsAboutTagline": "macOS Native AI Assistant",
        "settingsAboutDescription": "Local Apple Silicon AI + Cloud LLMs\nSystem Control \u{00B7} Code Assistance \u{00B7} Natural Conversation",
        "settingsHelperUnknown": "Unknown",
        "settingsHelperNotInstalled": "Not Installed",
        "settingsHelperInstalled": "Installed",
        "settingsHelperInstalling": "Installing...",
        "settingsHelperConnected": "Connected",
        "settingsHelperError": "Error: %@",
        "settingsProjectNotDetected": "No project detected",
        "settingsRequest": "Request",
        "settingsOpenSettings": "Settings",
    ]

    private static let zh: [String: String] = [
        "auditViewTitle": "操作审计",
        "auditViewSubtitle": "所有安全模式触发的操作记录",
        "auditExport": "导出",
        "auditSearchPlaceholder": "搜索操作记录…",
        "auditTotal": "总计",
        "auditDenied": "已拦截",
        "auditPending": "待审核",
        "auditHeader": "时间\t操作\t分类\t风险\t状态\t详情",
        "auditStatusApproved": "已放行",
        "auditStatusDenied": "已拦截",
        "auditStatusPending": "待审核",
        "auditStatusFailed": "执行失败",

        "dashboardTitle": "上下文仪表盘",
        "dashboardSubtitle": "当前环境信息与风险概览",
        "dashboardRefreshed": "上下文已刷新",
        "dashboardScreenWindow": "屏幕与窗口",
        "dashboardClipboardRisk": "剪贴板风险",
        "dashboardClipboardSafe": "当前剪贴板内容安全",
        "dashboardPermissions": "权限状态",
        "dashboardLastCheck": "上次检查: ",
        "dashboardDevContext": "开发上下文",
        "dashboardUncommitted": " 个未提交",
        "dashboardWorkspaceClean": "工作区干净",
        "dashboardRefreshContext": "刷新上下文",
        "dashboardCheckPassed": "全部通过",
        "dashboardCheckRunning": "运行中…",
        "dashboardCheckFailed": "%d 个失败",

        "assistantConfirmAction": "确认动作",
        "assistantExecute": "执行",
        "assistantCancel": "取消",
        "assistantQuitTitle": "退出 RenJistroly",
        "assistantQuitMessage": "确定要退出 RenJistroly 吗？",
        "assistantQuit": "退出",
        "assistantSidebar": "侧边栏",
        "assistantListening": "聆听中",
        "assistantTranscribing": "转写中",
        "assistantNewConversation": "新建对话",
        "assistantRefreshContext": "刷新上下文",
        "assistantReadScreen": "读取屏幕",
        "assistantPermissions": "权限",
        "assistantBaseCenter": "基础中心",
        "assistantSettings": "设置",
        "assistantContextPanel": "上下文面板",
        "assistantExit": "退出",
        "assistantInputPlaceholder": "输入消息开始对话，或点击麦克风使用语音输入",
        "assistantContextSection": "上下文",
        "assistantCurrentApp": "当前 App",
        "assistantUnknown": "未知",
        "assistantNoWindowTitle": "无窗口标题",
        "assistantListeningStatus": "正在听...",
        "assistantLockedListening": "持续监听...",
        "assistantSpeaking": "朗读中...",
        "assistantProcessing": "处理中...",
        "assistantExecutingPlan": "执行计划...",
        "assistantAwaitingApproval": "等待批准",
        "assistantPlanCompleted": "计划完成",
        "assistantPlanFailed": "计划失败",
        "assistantReady": "就绪",
        "assistantLoading": "加载中...",
        "assistantContextRunningApps": "运行中",
        "assistantContextFocusedElement": "焦点元素",
        "assistantPermissionAccessibility": "辅助功能",
        "assistantPermissionMicrophone": "麦克风",
        "assistantPermissionScreenRecording": "屏幕录制",
        "assistantContextRole": "角色",
        "assistantContextTitle": "标题",
        "assistantContextSelected": "选中",
        "mainTabControlPanel": "控制面板",
        "mainTabAuditLog": "审计日志",
        "mainTabDashboard": "上下文",
        "mainTabModeCountFormat": "%d/%d 安全模式已启用",
        "appDelegateAlreadyRunningTitle": "RenJistroly 已在运行",
        "appDelegateDuplicateInstanceBody": "检测到已有 RenJistroly 实例在运行。多个实例会导致 Gate 文件冲突。是否退出此实例？",
        "appDelegateContinueRunning": "继续运行",
        "appDelegateSafeModeTitle": "RenJistroly 进入安全模式",
        "appDelegateSafeModeBody": "检测到应用连续崩溃多次。已禁用部分自动功能（如 MCP 自动启动）。\n\n如需重置崩溃记录，请删除 ~/Library/Logs/RenJistroly/crash_history.json",
        "appDelegateAcknowledge": "了解",
        "appDelegateSettingsWindowTitle": "RenJistroly 设置",
        "appDelegateAppNapReason": "RenJistroly 需要持续后台活动以保持语音和屏幕监听",
        "appDelegatePermissionTitle": "需要辅助功能权限",
        "appDelegatePermissionBody": "RenJistroly 需要辅助功能权限来控制您的 Mac。\n\n请在系统设置 > 隐私与安全性 > 辅助功能中，添加并启用 RenJistroly。",
        "appDelegateOpenSystemSettings": "打开系统设置",
        "appDelegateLater": "稍后",

        "settingsTabGeneral": "通用",
        "settingsTabAIModel": "AI 模型",
        "settingsTabSecurity": "安全",
        "settingsTabDeveloper": "开发者",
        "settingsTabPermissions": "权限",
        "settingsTabAbout": "关于",
        "settingsGeneralStartupAppearance": "启动与外观",
        "settingsLaunchAtLogin": "开机自动启动",
        "settingsShowMenuBarIcon": "在菜单栏显示图标",
        "settingsEnableFloatingPanel": "启用浮动面板",
        "settingsDefaultAIProvider": "默认 AI 提供者",
        "settingsDefaultModel": "默认模型",
        "settingsInteraction": "交互",
        "settingsVoiceReply": "启用语音回复",
        "settingsContinuousVoice": "连续语音模式",
        "settingsGlobalHotkey": "全局热键",
        "settingsHotkeyValue": "按住 ⌥ Space",
        "settingsVoiceLanguage": "语音语言",
        "settingsChinese": "中文",
        "settingsJapanese": "日本語",
        "settingsToolAutoExecutePolicy": "工具自动执行策略",
        "settingsToolPolicyDescription": "控制 AI 助手执行系统操作时是否需要确认。",
        "settingsLowRiskAuto": "低风险 · 自动执行",
        "settingsLowRiskDesc": "只读操作：读取文件、列出目录、系统信息、Git状态等",
        "settingsMediumRiskAuto": "中风险 · 自动执行",
        "settingsMediumRiskDesc": "UI交互：打开应用、点击元素、按键、菜单导航等",
        "settingsHighRiskAuto": "高风险 · 自动执行",
        "settingsHighRiskDesc": "系统修改：写入文件、Shell命令、文字输入、拖拽等",
        "settingsPresets": "预设",
        "settingsPresetDefault": "默认",
        "settingsPresetDefaultDesc": "低风险自动，中高风险确认",
        "settingsPresetPermissive": "宽松",
        "settingsPresetPermissiveDesc": "低中风险自动，仅高风险确认",
        "settingsPresetStrict": "严格",
        "settingsPresetStrictDesc": "全部需要确认",
        "settingsAnthropic": "Anthropic (Claude)",
        "settingsApiKeyPlaceholder": "API Key",
        "settingsGetApiKeyPrefix": "获取 API Key:",
        "settingsLocalMLX": "本地模型 (MLX)",
        "settingsMLXStatus": "状态",
        "settingsMLXAvailable": "Apple Silicon · 可用",
        "settingsMLXDescription": "本地模型在 Apple Silicon 上运行，无需联网，数据安全",
        "settingsDevMode": "开发者模式",
        "settingsEnableDevMode": "启用开发者模式",
        "settingsProjectPath": "项目路径",
        "settingsDetect": "检测",
        "settingsOCREngine": "OCR 引擎",
        "settingsOCREnginePicker": "文字识别引擎",
        "settingsClaudeCodeReady": "Claude Code 已可用",
        "settingsClaudeCodeNotDetected": "Claude Code 未检测到",
        "settingsClaudeCodeRefresh": "刷新",
        "settingsCurrentProject": "当前项目",
        "settingsClaudeCodePromptPlaceholder": "给 Claude Code 的任务，例如：阅读当前 Swift Package 并总结未完成的能力",
        "settingsSavePath": "保存路径",
        "settingsLaunchClaudeTask": "启动 Claude 任务",
        "settingsClaudeCodeHelp": "Claude Code 会在当前项目目录中执行开发任务，并把输出流式返回到对话区。",
        "settingsClaudeCodeNotInstalledHelp": "请确认 Claude Code CLI 已安装，并把可执行文件路径填写到上方。",
        "settingsQuickActions": "快速操作",
        "settingsBuildResult": "构建完成: %@",
        "settingsBuild": "构建",
        "settingsTestResult": "测试完成: %@",
        "settingsTest": "测试",
        "settingsRecentBuild": "最近构建: %@",
        "settingsRecentTest": "最近测试: %@",
        "settingsSelfUpdate": "Self-Update",
        "settingsHelperLabel": "Helper: %@",
        "settingsCheck": "检查",
        "settingsCurrentVersion": "当前版本",
        "settingsInstallHelper": "安装 Helper",
        "settingsNoResponse": "无响应",
        "settingsVerifySignature": "验证签名",
        "settingsPermissionStatus": "权限状态",
        "settingsRefresh": "刷新",
        "settingsSystemPermissions": "系统权限",
        "settingsNotRefreshed": "尚未刷新。",
        "settingsPrivacy": "隐私",
        "settingsPrivacyText": "所有语音处理在本地完成，对话敏感数据不会离开设备。云端 API 调用仅发送必要的对话内容，且完全由您控制的 API Key 完成。",
        "settingsVersion": "版本",
        "settingsAboutTagline": "macOS 原生智能助手",
        "settingsAboutDescription": "本地 Apple Silicon AI + 云端大模型\n系统控制 · 代码辅助 · 自然对话",
        "settingsHelperUnknown": "未知",
        "settingsHelperNotInstalled": "未安装",
        "settingsHelperInstalled": "已安装",
        "settingsHelperInstalling": "安装中...",
        "settingsHelperConnected": "已连接",
        "settingsHelperError": "错误: %@",
        "settingsProjectNotDetected": "未检测到项目",
        "settingsRequest": "请求",
        "settingsOpenSettings": "设置",
    ]
}
